# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f41dddd22d69ed143d336c62080874427cf9c8c9c58fbe9b3bb7c52e176b7d7b2680537053ab122dbddfc9209d6527ed5b3f9388360f363bee46be7c1375ec4a

test:
  secret_key_base: bb43b0a8fb1f41d5c2bc601ef0e25084538dd0d3fdf7bf0f4c052ae92ce8f266639ab774d6568dc43fa8fdb58b1ed509362f8a47dadb1b23a60ea94ec32ee219

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
